name: Envoi automatique bulletin BRVM

on:
  schedule:
    - cron: '30 8 * * *'
  workflow_dispatch:

jobs:
  send-bulletin:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installer les dépendances
        run: pip install requests beautifulsoup4

      - name: Exécuter le script
        env:
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVERS: ${{ secrets.EMAIL_RECEIVERS }}
        run: python brvm.py
